python3 ./chameleon_continue_train.py \
--load_fn ./models/chameleon.transformer.05.1.46-4.32.1.42-4.14.pth \
--model_fn ./models/chameleon.transformer.rl.pth \
--train_fn ./data/chameleon.train.tok.pickle \
--valid_fn ./data/chameleon.valid.tok.pickle \
--src_tgt koen \
--with_text 1 \
--gpu_id 0 \
--batch_size 64 \
--n_epochs 5 \
--max_length 512 \
--dropout .2 \
--hidden_size 768 \
--n_layers 4 \
--max_grad_norm 1e+8 \
--iteration_per_update 2 \
--lr 1e-3 \
--lr_step 0 \
--use_adam \
--use_transformer \
--use_mps \
--rl_n_epochs 20 \
--init_epoch 6 \
--rl_n_samples 3
